services:
  postgres:
    image: postgres:16
    container_name: vendo-postgres
    environment:
      POSTGRES_DB: vendo_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - vendo_postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    container_name: vendo-backend
    depends_on:
      - postgres
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/vendo_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend/vendo
    container_name: vendo-frontend
    depends_on:
      - backend
    ports:
      - "5173:80"

volumes:
  vendo_postgres_data: